# Generated by Django 4.2.1 on 2023-06-15 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('specialization', models.CharField(choices=[('Dermatologist', 'Dermatologist'), ('Dentist', 'Dentist'), ('Sexologist', 'Sexologist'), ('Dietitian/Nutritionist', 'Dietitian/Nutritionist'), ('General Physician', 'General Physician'), ('Orthopedist', 'Orthopedist'), ('Gynaecologist', 'Gynaecologist'), ('Pediatrics', 'Pediatrics'), ('Psychologist', 'Psychologist')], max_length=100)),
                ('document', models.FileField(upload_to='doctor_document')),
                ('photo', models.ImageField(blank=True, default='user_avatar.png', upload_to='doctor_photo')),
                ('is_verified', models.BooleanField(default=False)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('experience', models.CharField(default='0', max_length=100)),
                ('about', models.TextField(blank=True, max_length=500, null=True)),
                ('fee', models.IntegerField(default=0)),
                ('hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, default='user_avatar.png', upload_to='patient_photo')),
                ('is_admin', models.BooleanField(default=False, max_length=5)),
                ('is_patient', models.BooleanField(default=False, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Revoke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(default='pending', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
        ),
    ]
