# Generated by Django 4.2.1 on 2023-06-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='revoke',
            name='code',
            field=models.CharField(blank=True, default='Tenassist:jOvdf', max_length=15),
        ),
    ]
