# Generated by Django 4.2.1 on 2023-06-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_revoke_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revoke',
            name='code',
            field=models.CharField(blank=True, default='265809', max_length=15),
        ),
    ]
