# Generated by Django 4.2.1 on 2023-06-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_revoke_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revoke',
            name='code',
            field=models.CharField(blank=True, default='937180', max_length=15),
        ),
        migrations.AlterField(
            model_name='revoke',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.doctor'),
        ),
        migrations.AlterField(
            model_name='revoke',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.patient'),
        ),
    ]
