# Generated by Django 4.2.1 on 2023-06-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_revoke_code_alter_revoke_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revoke',
            name='code',
            field=models.CharField(blank=True, default='624928', max_length=15),
        ),
    ]
