# Generated by Django 4.2.1 on 2023-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_revoke_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='revoke',
            name='ran',
            field=models.CharField(default='629233', max_length=6),
        ),
        migrations.AlterField(
            model_name='revoke',
            name='code',
            field=models.CharField(blank=True, default=models.CharField(default='629233', max_length=6), max_length=15),
        ),
    ]
