# Generated by Django 4.2.1 on 2023-06-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_revoke_ran_alter_revoke_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revoke',
            name='code',
        ),
        migrations.AlterField(
            model_name='revoke',
            name='ran',
            field=models.CharField(default='403707', max_length=6),
        ),
    ]
