# Generated by Django 4.2.1 on 2024-03-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_revoke_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
