# Generated by Django 4.2.1 on 2023-06-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
