# Generated by Django 4.2.1 on 2023-06-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_delete_prescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
