# Generated by Django 4.2.1 on 2023-06-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_revoke_code'),
        ('appointment', '0007_appday_appadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appday',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appday',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.patient'),
        ),
    ]
