# Generated by Django 4.2.1 on 2023-06-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_revoke_code'),
        ('appointment', '0008_remove_appday_doctor_appday_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appadmin',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.doctor', unique=True),
        ),
    ]
