# Generated by Django 4.2.1 on 2023-06-24 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_alter_appadmin_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appadmin',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.appday'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointment.workingday'),
        ),
    ]
