# Generated by Django 4.2.1 on 2023-06-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0010_alter_appadmin_schedule_alter_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appadmin',
            name='attendee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appadmin',
            name='host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='attendee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
