# Generated by Django 4.2.1 on 2023-06-10 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=21)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.patient')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
