# Generated by Django 4.2.1 on 2023-06-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='rate',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
