# Generated by Django 4.2.1 on 2023-06-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_prescription_medicalhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name_plural': 'MedicalHistories'},
        ),
        migrations.RenameField(
            model_name='medicalhistory',
            old_name='is_show',
            new_name='is_shown',
        ),
    ]
