# Generated by Django 4.2.1 on 2023-06-23 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_delete_appointment'),
        ('dashboard', '0006_alter_medicalhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_rate', to='account.doctor'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rate', to='account.patient'),
        ),
    ]
