# Generated by Django 4.2.1 on 2023-06-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_rate_doctor_alter_rate_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='user',
            new_name='patient',
        ),
    ]
