# Generated by Django 4.2.1 on 2023-06-25 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_revoke_code'),
        ('dashboard', '0009_alter_prescription_doctor_alter_prescription_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mdoctor', to='account.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mhistory', to='account.patient'),
        ),
    ]
